const webTitle = 'AP | Editor'

export default {
    webTitle,
    metaHtml: { title: { variable: 'META_TITLE', value: webTitle } },
    syntaxes: [
        { label: 'Plain Text', value: '' },
        { label: 'JavaScript', value: 'javascript' },
        { label: 'HTML', value: 'html' },
        { label: 'CSS', value: 'css' },
        { label: 'Python', value: 'python' },
        { label: 'Java', value: 'java' },
        { label: 'C++', value: 'cpp' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'PHP', value: 'php' },
        { label: 'Swift', value: 'swift' },
        { label: 'TypeScript', value: 'typescript' },
        { label: 'Go', value: 'go' },
        { label: 'Kotlin', value: 'kotlin' },
        { label: 'Rust', value: 'rust' },
        { label: 'Scala', value: 'scala' },
        { label: 'SQL', value: 'sql' },
        { label: 'JSON', value: 'json' },
        { label: 'Markdown', value: 'markdown' },
        { label: 'XML', value: 'xml' },
        { label: 'YAML', value: 'yaml' },
        { label: 'Bash', value: 'bash' },
        { label: 'Dockerfile', value: 'dockerfile' },
        { label: 'GraphQL', value: 'graphql' },
        { label: 'Makefile', value: 'makefile' },
        { label: 'Perl', value: 'perl' },
        { label: 'PowerShell', value: 'powershell' },
        { label: 'SCSS', value: 'scss' },
        { label: 'Shell', value: 'shell' },
        { label: 'Vue.js', value: 'vue' },
        { label: 'XML', value: 'xml' },
    ],
}
