const webTitle = 'Aprograma Editor';

export default {
    webTitle,
    translatableSuffix: '__i18n__',
    languages: ['en', 'es', 'it'],
    metaHtml: { title: { variable: 'META_TITLE', value: webTitle } },
    manifest: {
        name: webTitle,
        short_name: webTitle,
        description: webTitle,
        theme_color: '#ffffff',
        icons: [
            {
                src: 'icons/icon-48x48.png',
                sizes: '48x48',
                type: 'image/png',
            },
            {
                src: 'icons/icon-72x72.png',
                sizes: '72x72',
                type: 'image/png',
            },
            {
                src: 'icons/icon-96x96.png',
                sizes: '96x96',
                type: 'image/png',
            },
            {
                src: 'icons/icon-128x128.png',
                sizes: '128x128',
                type: 'image/png',
            },
            {
                src: 'icons/icon-144x144.png',
                sizes: '144x144',
                type: 'image/png',
            },
            {
                src: 'icons/icon-152x152.png',
                sizes: '152x152',
                type: 'image/png',
            },
            {
                src: 'icons/icon-192x192.png',
                sizes: '192x192',
                type: 'image/png',
            },
            {
                src: 'icons/icon-512x512.png',
                sizes: '512x512',
                type: 'image/png',
            },
        ],
    },
    syntaxes: [
        { label: 'Plain Text', value: '' },
        { label: 'JavaScript', value: 'javascript' },
        { label: 'HTML', value: 'html' },
        { label: 'CSS', value: 'css' },
        { label: 'Python', value: 'python' },
        { label: 'Java', value: 'java' },
        { label: 'C++', value: 'cpp' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'PHP', value: 'php' },
        { label: 'Swift', value: 'swift' },
        { label: 'TypeScript', value: 'typescript' },
        { label: 'Go', value: 'go' },
        { label: 'Kotlin', value: 'kotlin' },
        { label: 'Rust', value: 'rust' },
        { label: 'Scala', value: 'scala' },
        { label: 'SQL', value: 'sql' },
        { label: 'JSON', value: 'json' },
        { label: 'Markdown', value: 'markdown' },
        { label: 'XML', value: 'xml' },
        { label: 'YAML', value: 'yaml' },
        { label: 'Bash', value: 'bash' },
        { label: 'Dockerfile', value: 'dockerfile' },
        { label: 'GraphQL', value: 'graphql' },
        { label: 'Makefile', value: 'makefile' },
        { label: 'Perl', value: 'perl' },
        { label: 'PowerShell', value: 'powershell' },
        { label: 'SCSS', value: 'scss' },
        { label: 'Shell', value: 'shell' },
        { label: 'Vue.js', value: 'vue' },
        { label: 'XML', value: 'xml' },
    ],
};
